export const speakerNotes = [
  `Music and sports run on the same fuel — elite talent, devoted fans, cultural obsession. Sports turned that into a $500 billion industry. Music is sitting at $54 billion with a $0 participation economy. The infrastructure that would close that gap has never been built. We're building it. One of the two products is already live.`,

  `The gap isn't about cultural relevance. Music reaches more people every day than any sport. The difference is structural. Sports built something around its art form that music never did. And the most telling number isn't the $446 billion total gap — it's that line at the bottom. The participation economy for music is literally zero. Not small. Not nascent. Zero. Fantasy sports, sports betting, prediction markets — that's a $200 billion downstream market built on top of organizational competition infrastructure. Music has streaming. That's it. That's what we're here to fix.`,

  `The pushback we get is that music isn't inherently competitive like sports. That misreads the causality. The NBA didn't create competition — basketball was already competitive. What the NBA built was the organizational layer around it. Leagues, teams, standardized metrics, transparent contracts, a governed format. That layer is what unlocked everything downstream. Music has the art form. It has the fans. It never got the organizational layer. That's the gap. LabelHead fills it.`,

  `Simple version: you build a label, you draft artists, you compete. You pick five artists you think are about to break — before the Cycle locks, your picks are public and timestamped. Then the real world runs. Streams, press, cultural heat — all scored from third-party data we don't control. The label that called it right wins real money. And the leaderboard is permanent, so the person who drafted Kendrick before everyone else gets credit for it forever. This isn't luck. It's the A&R instinct — knowing who's about to break before the data confirms it — formalized for the first time.`,

  `I could show you screenshots. Let me just pull it up.

[Navigate live to app.labelhead.co. Show roster selection, live leaderboard, one artist's scoring breakdown. 90 seconds.]

The scoring engine is running on live Spotify and third-party data right now. Everything you just saw is real. This is not a prototype. It's Founding Season infrastructure — operational before we raised a dollar.`,

  `I want to be upfront about something. LabelHead is live. Brazen is in development. You might see that as an asymmetry. We see it as the thesis in action — we built the competition infrastructure first because it's the asset that makes everything else downstream more valuable, including Brazen. LabelHead doesn't need Brazen to be a real business. It has its own revenue model. Brazen is the multiplier. And this raise funds both — the GTM activation for LabelHead and the Brazen MVP — so when the Series A conversation starts, we're showing two operational properties, not a deck.`,

  `Brazen is not a music app. It's a multi-channel vertical content network. LabelHead is Channel One — and it proves the core thesis before we shoot a single original frame. The competition generates a daily programming schedule automatically. No writers' room. No editorial calendar. The scores update, the leaderboard moves, and Brazen has a news cycle. The original programming — the documentaries, the prestige series, The Rollout — that's Marcus's domain. His production track record gives Brazen access to artists and stories that no streaming service can buy from the outside. We're not naming Channel Two today. Channel One is the proof. The investor is buying the architecture.`,

  `The flywheel is why this is a company and not two separate products. LabelHead needs cultural distribution — Brazen provides it. Brazen needs a reason to come back every day — LabelHead provides it through the Cycle. But the most important node isn't either property. It's the data layer. Every draft pick is a timestamped prediction. At scale, the aggregate of those predictions is a cultural conviction dataset that doesn't exist anywhere. That's the Label Intelligence API — a B2B product we sell to A&R teams, DSPs, and music rights investors who have no equivalent source. You can't buy that data. It has to be accumulated one Cycle at a time. Every day Founding Season runs, the moat deepens.`,

  `Two separate market stories. The first: the participation economy for music is currently zero, inside a music industry that's growing at 10% annually and sitting at historic revenue highs. The $200 billion sports comparison is where this category goes when it has infrastructure — not where we start. The second story is Brazen, and it's bigger. A multi-channel vertical content network isn't limited to music. The platform architecture we're building can address any cultural vertical where organized competition or premium original programming can sustain an audience. We're not pitching that TAM today. We're pitching Channel One. But investors should know the architecture scales well beyond music.`,

  `The sequence is the strategy. Everything depends on what comes before it. The demo video is produced first — it's the answer to "what is this?" and every creator on Ranked, every podcast listener, every person who sees the NLE spot needs somewhere to go. NLE is Marcus's relationship — talent is structured as equity, so a culturally credible spot costs us a fraction of the commercial rate. Then the podcast hosts. We don't sponsor their shows — we make them participants. They compete against each other, publicly, with real skin in the game. Their feud is LabelHead's founding narrative. Their combined audience becomes the media kit that closes the anchor sponsor. The demo unlocks Ranked. Ranked and NLE unlock the podcast play. The podcast play assembles the Top 50. The Top 50 closes the sponsor. That's the chain.`,

  `The question I get is: what if the sponsor doesn't close? Here's why that question understates the position we'll be in. We're not cold-pitching a concept. We're walking into a meeting with a confirmed list of fifty culturally recognized people competing publicly on LabelHead — with their combined reach documented, weekly content volume projected, and a media kit that competes directly with a mid-tier network TV buy. At $250K to $1M, that's a fraction of what equivalent reach costs in traditional media. Plus category exclusivity and a full season arc. Hennessy, Cîroc, Don Julio — these brands have spent decades fighting for exactly this audience through festival sponsorships and album placements. We're giving them something none of those vehicles offer. One brand gets in. The others miss the window. That urgency is on their side, not ours. And we don't announce the prize until the check clears.`,

  `The model stages deliberately. Founding Season is about proof of concept and closing the sponsor — that sponsor funds the prize, not this raise. Season 2 is where revenue diversifies around proven infrastructure — artist portals, subscriptions, Brazen co-productions. Season 3 is when the B2B data product launches — by then we have multiple full Cycles of conviction data that no A&R team can access anywhere else. Season 4 is institutional — real labels fielding official rosters turns LabelHead into the governing body of music's competitive layer. Each season makes the next revenue conversation easier because the data compounds and the Brazen channel architecture expands.`,

  `Seed-stage companies with live operational products are a different category of investment than pre-product pitches. The scoring engine isn't a prototype — it's running on real streaming data with real outcomes. We built it before this raise on a fraction of what it would cost a traditionally-run company. That's not luck. The Paperclip agent system handles functions that would require a team of fifteen elsewhere. Platform being live before the raise tells you two things: we can build, and we can do it efficiently. What the raise unlocks is the activation that turns a working platform into a cultural moment — and the Brazen MVP that gives the second property a foundation.`,

  `Two things to flag. First — the prize pool isn't in here. Prize pool capital and investor capital should never sit in the same column. The prize is a brand's marketing activation. This raise creates the conditions that make a brand's yes easy — a live platform, a confirmed Top 50, documented reach, and a season arc with weekly content. We walk into that sponsor meeting with a media package, not a pitch for what could happen. Second — why $1.2M. We built LabelHead before the raise. The original scope was GTM only. But this deck describes Sovereign — two properties, a flywheel, a data asset. Raising GTM capital only for a company of that scope is undercapitalized in a way investors notice. This raise funds the Brazen MVP alongside the GTM activation. By the time we're in the Series A conversation, both properties are operational. That's a materially stronger position to raise from.`,

  `Sports has leagues. Culture has Sovereign. LabelHead is live before we raised a dollar. Brazen has a raise behind its foundation. The data starts accumulating the moment Founding Season opens — and every Cycle that runs, the asset deepens and the moat gets harder to replicate. We're raising $1.2 million to launch the first season at the cultural scale it deserves, build the second property into something real, and set up a Series A with two operating companies behind it. Let's talk.`
];
